name: 03-dependent-jobs

on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Darbs sastāv no"
      - run: echo "viena vai vairākiem soļiem,"
      - run: echo "kuri tiek izpildīti secīgi"
      - run: echo "vienā aprēķinu vidē (computing environment)"
  job-2:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Vaidāki darbi var izpildīties parallēli"
  job-3:
    runs-on: ubuntu-24.04
    needs:
      - job-1
      - job-2
    steps:
      - run: echo "Tie arī var būt atkarīgi viens no otra ..."
  job-4:
    runs-on: ubuntu-24.04
    needs:
      - job-2
      - job-3
    steps:
      - run: echo "... ar to veidojot orientēto aciklisko grafu (directed acyclic graph (DAG))"