name: 05-vides-mainigie
on:
  workflow_dispatch:
env:
  WORKFLOW_VAR: ES_ESMU_GLOBALAIS_DARBA_PLUSMAS_MAINIGAIS

jobs:
  job-1:
    runs-on: ubuntu-24.04
    env:
      JOB_VAR: ES_ESMU_DARBA_JOB-1_MAINIGAIS
    steps:
      - name: Apskatīt job-1 step-1 stāvokli (scope)
        env:
          STEP_VAR: ES_ESMU_DARBA_JOB-1_STEP-1_MAINIGAIS
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"   # redzams
          echo "JOB_VAR:      $JOB_VAR"        # redzams
          echo "STEP_VAR:     $STEP_VAR"       # redzams tikai šeit

      - name: Apskatīt job-1 step-2 stāvokli (scope)
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"         # redzams
          echo "JOB_VAR:      $JOB_VAR"              # redzams
          echo "STEP_VAR:     ${STEP_VAR:-<UNSET>}"  # nav redzams - nav definēts

  job-2:
    runs-on: ubuntu-24.04
    steps:
      - name: Apskatīt job-2 step-1 stāvokli (scope)
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"                 # redzams
          echo "JOB_VAR:      ${JOB_VAR:-<UNSET>}"               # nav redzams - nav definēts
          echo "STEP_VAR:     ${STEP_VAR:-<UNSET>}"          # nav redzams - nav definēts